import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Image src="/cosmotunes-logo.png" alt="Cosmotunes Logo" width={250} height={200} style={{
          marginTop: "-65px",
          textShadow: "10px 10px 10px rgba(255, 255, 255, 1)",
        }} />
        {children}
      </body>
    </html>
  );
}
